# Generated by Django 4.0.4 on 2022-06-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactm',
            old_name='name',
            new_name='username',
        ),
    ]
